### ISSUE TITLE
fail to build arm64 and x86_64  so

### ISSUE THREAD

**Issue by realtime29** [ButterflyTV/LibRtmp-Client-for-Android#9]

**Comment by mekya** [comment]
Have you encountered any error?

**Comment by tmhouse** [comment]
It is very simple there are no 64bit libs.
I didn't know how to make them, but I just did it.
Change compileSdkVersion number greater equal 21. 
that's all.

And, please upload new version to maven(?) repository.

thank your nice source!

**Comment by mekya** [comment]
Your welcome,

if compileSdkVersion is set to 21, there are errors on previous versions so that we made it to 16.
Theoritcally 32 bit is compatible with 64 bit and I also have compiled this library for 64 bit architectures but I didn't package them all because of not to increase the size of the lib.

**Comment by Furystorm** [comment]
According to [this](http://ph0b.com/android-abis-and-so-files/) article, providing all the files for each architectures is a good idea. If there is no .so files for 64 bit architectures in this lib, users can not use 64 bit in other libs.

> If you’re a library provider, and you’re not supporting all the ABIs, you’re screwing up your customers, as they can’t support more ABIs than you do.

**Comment by calber** [comment]
not including 64 bit is a bad idea, if you mix rtmp with other jni lib with 64bit support, rtmp crashes as it expect to find so in the existing 64 bit directory, but it's not there...

**Comment by mekya** [comment]
@calber probably your project uses some other 64bit libs and android is only looking for the 64bit directory to find librtmp.     

if we set to compile sdk to 21, 64 bits .so are created. However then we need to set the minimumSdkLevel to 21 as well otherwise it throws exceptions in older sdk levels than to 21. These are pros and cons please build the lib according to your project. 

Please comment it if you have something to say.

Bests,
